INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'colorjitter', 'normalize']

DATASET:
  NAME: 'OfficeHomeDG'

MODEL:
  BACKBONE:
    NAME: 'odresnet50_4x_v5'
    PRETRAINED: True
  INIT_WEIGHTS: '../checkpoints/odconv4x_resnet50.pth.tar'
